### ISSUE TITLE
script fails to initiate call

### ISSUE THREAD

**Issue by chrisjscott** [PaperCutSoftware/teleportme#12]
Using 10.10.3 w/ Facetime v3.0, the:

tell application "System Events"
     keystroke return
end tell

in make_facetime_call() fails to initiate the call - manually pressing the return key also fails. Any thoughts?

**Comment by alecthegeek** [comment]
We have not upgraded our portal system to X.10.3 so we are not yet seeing this. I'll have a look, but it will take a bit of time.

**Comment by codedance** [comment]
Yes.  10.10 is a known problem.  This is related to #9 . We haven't yet solved it.  

There may be something we can do through the "accessibility" API to automate the calling process.  I'll see if we can book out some time over the next week or so and done a bit more R&D.  At the moment our recommendation is to stick with 10.9.
