### ISSUE TITLE
Auto Accept calls on Mojave.

### ISSUE THREAD

**Issue by mdio33** [PaperCutSoftware/teleportme#18]
Hello,
I've found your teleportme script and it is all I need for a project, but I can't make the Receiver to auto accept the call, even if I manualy add this command

"defaults write com.apple.FaceTime AutoAcceptInvitesFrom -array-add email-caller@address.com"

If i manual accept the call everything works great.

Does it have any issues with Mojave?
Thank you.

**Comment by alecthegeek** [comment]
I am sorry, this project is not currently being used by us so we don't have any updates
